version: 2
jobs:
  build:
    docker:
      - image: mmgeorge/sbcl:latest
    steps:
      - checkout:
          path: ~/common-lisp/sly-asdf
      - run:
          name: Update
          command: cd ~/common-lisp/sly-asdf && git pull
      - run:
          name: Download sly
          command: git clone https://github.com/joaotavora/sly ~/common-lisp/sly --depth 1
      - run:
          name: Load package
          command:  sbcl --eval '(asdf:load-system "slynk-asdf")' --non-interactive
